# Generated by Django 2.2 on 2020-01-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedgame',
            name='progress',
            field=models.TextField(blank=True),
        ),
    ]
