# Generated by Django 2.2.7 on 2020-01-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameLibrary', '0002_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='Game Description'),
        ),
    ]
