# Generated by Django 2.2.7 on 2020-01-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameLibrary', '0003_auto_20200107_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='highscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
