# Generated by Django 3.0.2 on 2020-01-09 09:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameLibrary', '0004_auto_20200107_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevelopedGame',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.RemoveField(
            model_name='ownedgame',
            name='user',
        ),
        migrations.AddField(
            model_name='ownedgame',
            name='bought_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ownedgame',
            name='highscore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ownedgame',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ownedgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameLibrary.Game'),
        ),
    ]
