# Generated by Django 2.2 on 2020-01-09 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameLibrary', '0005_auto_20200109_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedgame',
            name='player',
            field=models.ForeignKey(blank=True, default='miikka', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
