# Generated by Django 2.2 on 2020-01-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameLibrary', '0008_auto_20200109_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedgame',
            name='player',
        ),
    ]
