# Generated by Django 2.2 on 2020-01-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameLibrary', '0011_auto_20200109_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
    ]
