# Generated by Django 2.2 on 2020-01-09 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameLibrary', '0012_remove_game_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games', through='gameLibrary.OwnedGame', to=settings.AUTH_USER_MODEL),
        ),
    ]
